In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('/content/Students Social Media Addiction.csv')

In [3]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

In [4]:
df.tail()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
700,701,20,Female,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,Male,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,Female,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [5]:
df.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

In [6]:
df1=df['Country']
df1

0      Bangladesh
1           India
2             USA
3              UK
4          Canada
          ...
700         Italy
701        Russia
702         China
703         Japan
704        Poland
Name: Country, Length: 705, dtype: object

In [7]:
df.loc[0]

Student_ID                                    1
Age                                          19
Gender                                   Female
Academic_Level                    Undergraduate
Country                              Bangladesh
Avg_Daily_Usage_Hours                       5.2
Most_Used_Platform                    Instagram
Affects_Academic_Performance                Yes
Sleep_Hours_Per_Night                       6.5
Mental_Health_Score                           6
Relationship_Status             In Relationship
Conflicts_Over_Social_Media                   3
Addicted_Score                                8
Name: 0, dtype: object

In [8]:
df.loc[1]

Student_ID                             2
Age                                   22
Gender                              Male
Academic_Level                  Graduate
Country                            India
Avg_Daily_Usage_Hours                2.1
Most_Used_Platform               Twitter
Affects_Academic_Performance          No
Sleep_Hours_Per_Night                7.5
Mental_Health_Score                    8
Relationship_Status               Single
Conflicts_Over_Social_Media            0
Addicted_Score                         3
Name: 1, dtype: object

In [9]:
df.loc[2:5]

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
5,6,19,Female,Undergraduate,Australia,7.2,Instagram,Yes,4.5,4,Complicated,5,9

In [10]:
df.loc[:,'Age']

0      19
1      22
2      20
3      18
4      21
       ..
700    20
701    23
702    21
703    24
704    19
Name: Age, Length: 705, dtype: int64

In [11]:
df1=df[['Age' ,'Gender']]
df1

     Age  Gender
0     19  Female
1     22    Male
2     20  Female
3     18    Male
4     21    Male
..   ...     ...
700   20  Female
701   23    Male
702   21  Female
703   24    Male
704   19  Female

[705 rows x 2 columns]

In [12]:
print(df[df['Age']>22])

     Student_ID  Age  Gender Academic_Level       Country  \
6             7   23    Male       Graduate       Germany
16           17   24    Male       Graduate        Sweden
21           22   23  Female       Graduate   Switzerland
28           29   24    Male       Graduate      Malaysia
33           34   23  Female       Graduate        Taiwan
40           41   24    Male       Graduate  South Africa
45           46   23  Female       Graduate         Chile
52           53   24    Male       Graduate       Bolivia
57           58   23  Female       Graduate       Bahamas
64           65   23    Male       Graduate      Slovakia
74           75   23    Male       Graduate       Belarus
87           88   23  Female       Graduate    San Marino
94           95   23    Male       Graduate        Bosnia
101         102   23  Female       Graduate          Iraq
108         109   23    Male       Graduate     Sri Lanka
571         572   23    Male       Graduate       Denmark
575         576   24    Male       Graduate        Turkey
579         580   23    Male       Graduate        Canada
581         582   24    Male       Graduate         Italy
585         586   23    Male       Graduate        Poland
587         588   24    Male       Graduate         Spain
591         592   23    Male       Graduate   Switzerland
593         594   24    Male       Graduate           USA
596         597   23  Female       Graduate        Canada
600         601   24  Female       Graduate         China
602         603   23  Female       Graduate        Poland
606         607   24  Female       Graduate       Ireland
608         609   23  Female       Graduate   Switzerland
612         613   24  Female       Graduate        France
614         615   23  Female       Graduate            UK
618         619   24  Female       Graduate         Japan
620         621   23  Female       Graduate       Finland
624         625   24  Female       Graduate         India
626         627   23  Female       Graduate        Turkey
630         631   24  Female       Graduate        Canada
632         633   23  Female       Graduate         Italy
636         637   24  Female       Graduate        Poland
638         639   23  Female       Graduate         Spain
642         643   24  Female       Graduate   Switzerland
644         645   23  Female       Graduate           USA
647         648   23    Male       Graduate        Canada
649         650   24    Male       Graduate         Italy
653         654   23    Male       Graduate        Poland
655         656   24    Male       Graduate         Spain
659         660   23    Male       Graduate   Switzerland
661         662   24    Male       Graduate           USA
665         666   23    Male       Graduate            UK
667         668   24    Male       Graduate        Russia
671         672   23    Male       Graduate       Finland
673         674   24    Male       Graduate       Denmark
677         678   23    Male       Graduate        Turkey
679         680   24    Male       Graduate        Mexico
683         684   23    Male       Graduate         Italy
685         686   24    Male       Graduate         China
689         690   23    Male       Graduate         Spain
691         692   24    Male       Graduate       Ireland
695         696   23    Male       Graduate           USA
697         698   24    Male       Graduate        France
701         702   23    Male       Graduate        Russia
703         704   24    Male       Graduate         Japan

     Avg_Daily_Usage_Hours Most_Used_Platform Affects_Academic_Performance  \
6                      1.5           LinkedIn                           No
16                     2.0           LinkedIn                           No
21                     2.5           LinkedIn                           No
28                     2.2           LinkedIn                           No
33                     2.6           LinkedIn                           No
40                     2.3           LinkedIn                           No
45                     2.7           LinkedIn                           No
52                     2.4           LinkedIn                           No
57                     2.8           LinkedIn                           No
64                     2.3           LinkedIn                           No
74                     2.5           LinkedIn                           No
87                     2.6           LinkedIn                           No
94                     2.4           LinkedIn                           No
101                    2.5           LinkedIn                           No
108                    2.6           LinkedIn                           No
571                    3.8            Twitter                           No
575                    6.8             TikTok                          Yes
579                    5.2          Instagram                          Yes
581                    4.9           Facebook                           No
585                    6.4           Facebook                          Yes
587                    6.6             TikTok                          Yes
591                    4.3           Facebook                           No
593                    5.6          Instagram                          Yes
596                    4.9             TikTok                           No
600                    5.5             WeChat                          Yes
602                    6.2          Instagram                          Yes
606                    5.9            Twitter                          Yes
608                    4.4          Instagram                           No
612                    4.8            Twitter                           No
614                    6.1             TikTok                          Yes
618                    4.2            Twitter                           No
620                    4.4          Instagram                           No
624                    7.0             TikTok                          Yes
626                    6.7          Instagram                          Yes
630                    5.6             TikTok                          Yes
632                    4.8            Twitter                           No
636                    6.1             TikTok                          Yes
638                    6.4           Facebook                          Yes
642                    4.6           Facebook                           No
644                    5.3            Twitter                          Yes
647                    5.7             TikTok                          Yes
649                    4.7           Facebook                           No
653                    6.2             TikTok                          Yes
655                    6.5           Facebook                          Yes
659                    4.5           Facebook                           No
661                    5.4            Twitter                          Yes
665                    6.3            Twitter                          Yes
667                    6.9          Instagram                          Yes
671                    4.3          Instagram                           No
673                    4.5            Twitter                           No
677                    6.8          Instagram                          Yes
679                    6.2           Facebook                          Yes
683                    4.8           Facebook                           No
685                    5.5             WeChat                          Yes
689                    6.5           Facebook                          Yes
691                    5.9          Instagram                          Yes
695                    5.5            Twitter                          Yes
697                    4.8           Facebook                           No
701                    6.8          Instagram                          Yes
703                    4.3            Twitter                           No

     Sleep_Hours_Per_Night  Mental_Health_Score Relationship_Status  \
6                      8.0                    9              Single
16                     7.8                    8              Single
21                     7.3                    8     In Relationship
28                     7.4                    8              Single
33                     7.2                    8              Single
40                     7.3                    8     In Relationship
45                     7.1                    8         Complicated
52                     7.2                    8         Complicated
57                     7.0                    8     In Relationship
64                     7.4                    8     In Relationship
74                     7.3                    8     In Relationship
87                     7.3                    8              Single
94                     7.4                    8         Complicated
101                    7.3                    8              Single
108                    7.2                    8     In Relationship
571                    7.8                    8     In Relationship
575                    6.2                    5              Single
579                    7.0                    6     In Relationship
581                    7.3                    7     In Relationship
585                    6.3                    5              Single
587                    6.2                    5              Single
591                    7.5                    7     In Relationship
593                    6.9                    6     In Relationship
596                    7.3                    7     In Relationship
600                    6.8                    6     In Relationship
602                    6.4                    5              Single
606                    6.6                    6              Single
608                    7.4                    7     In Relationship
612                    7.3                    7     In Relationship
614                    6.4                    5              Single
618                    7.5                    8              Single
620                    7.4                    7     In Relationship
624                    5.8                    4              Single
626                    6.1                    5              Single
630                    6.7                    6              Single
632                    7.1                    7     In Relationship
636                    6.4                    5              Single
638                    6.2                    5              Single
642                    7.2                    7     In Relationship
644                    6.8                    6     In Relationship
647                    6.6                    6              Single
649                    7.2                    7     In Relationship
653                    6.3                    5              Single
655                    6.1                    5              Single
659                    7.3                    7     In Relationship
661                    6.8                    6     In Relationship
665                    6.2                    5              Single
667                    5.9                    4              Single
671                    7.5                    7     In Relationship
673                    7.3                    7     In Relationship
677                    6.0                    5              Single
679                    6.3                    5              Single
683                    7.1                    7     In Relationship
685                    6.8                    6     In Relationship
689                    6.1                    5              Single
691                    6.5                    6              Single
695                    6.7                    6     In Relationship
697                    7.1                    7     In Relationship
701                    5.9                    4              Single
703                    7.5                    8              Single

     Conflicts_Over_Social_Media  Addicted_Score
6                              0               2
16                             0               3
21                             1               4
28                             0               3
33                             1               4
40                             1               4
45                             1               4
52                             1               4
57                             1               4
64                             1               3
74                             1               4
87                             1               4
94                             1               4
101                            1               4
108                            1               4
571                            2               4
575                            4               8
579                            3               6
581                            2               5
585                            4               8
587                            4               8
591                            2               5
593                            3               7
596                            2               5
600                            3               7
602                            4               8
606                            3               7
608                            2               5
612                            2               5
614                            4               8
618                            2               4
620                            2               5
624                            5               9
626                            4               8
630                            3               7
632                            2               5
636                            4               8
638                            4               8
642                            2               5
644                            3               7
647                            3               7
649                            2               5
653                            4               8
655                            4               8
659                            2               5
661                            3               7
665                            4               8
667                            5               9
671                            2               5
673                            2               5
677                            4               8
679                            4               8
683                            2               5
685                            3               7
689                            4               8
691                            3               7
695                            3               7
697                            2               5
701                            5               9
703                            2               4

In [13]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Relationship_Status             0
Conflicts_Over_Social_Media     0
Addicted_Score                  0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.drop_duplicates(inplace=True)